### PR TITLE
[DONE] once in a lifetime

### PR DESCRIPTION
**Pull request by matklad**
Trying to fix https://github.com/GabrielCastro/neon-serde/issues/4 :)

### CODE REVIEW

**Comment by matklad** [comment]
Wait, there are a lot of node-based tests here, I've missed them all at first because `cargo tests` does not use them! I don't know how to execute them locally (have only vague ideas about yarn), hopefully CI will be enough to trouble shoot all the problems :)

**Comment by matklad** [comment]
Looks like I've broken some tests, so the test suite is really solid!

I am not sure I'll soon have time to look Into test failures, so feel free to move this over the finish line!

**Comment by matklad** [comment]
Ok, so now this passes all the tests, and works with my neon-based project just fine!

**Comment by nixpulvis** [comment]
FWIW, I'll try to look over this sometime, maybe by this weekend.

**Comment by nixpulvis** [comment]
I personally wouldn't rename `from_handle` to `from_value`.

**Comment by nixpulvis** [comment]
Using this branch I've gotten the following to work. Which seems to solve my issue with borrows.

```rust
#[macro_use]
extern crate neon;
extern crate neon_serde;

use neon::vm::{Call, JsResult};
use neon::js::JsNumber;

fn fibonacci(n: u64) -> u64 {
    match n {
        0 | 1 => 1,
        _ => fibonacci(n - 1) + fibonacci(n - 2)
    }
}

fn fib(call: Call) -> JsResult<JsNumber> {
    let scope = call.scope;
    let value = call.arguments.require(scope, 0)?;
    let argument = neon_serde::from_value(scope, value)?;
    let result = fibonacci(argument);
    Ok(JsNumber::new(scope, result as f64))
}

register_module!(m, {
    m.export("fib", fib)
});
```

**Comment by matklad** [comment]
>I personally wouldn't rename from_handle to from_value.

This mirrors serde-json, and `to_value/from_value` seems more symmetric and obvious than `to_value/from_handle`.

**Comment by matklad** [comment]
>I personally wouldn't rename from_handle to from_value.

I definitely should not have done this in this PR though :) I've got carried away a bit :(

**Comment by sebasmagri** [comment]
This made it feasible for me to use neon_serde as well... Thanks @matklad.

**Comment by GabrielCastro** [comment]
Thank you so much, I was pulling my hair out a lot over this one

**Pull request merged**
