### PR TITLE
Cargo.toml: Bump the versions of neon and the neon-runtime.

### PR DESCRIPTION
**Pull request by poljar**
This just bumps the neon version dependencies, since there's a new neon release.
Tested with a project that it works as expected. Nothing seems to be broken.

Would be nice to get a release out with the bumped dependencies.

Thanks.

### CODE REVIEW

**Comment by pimeys** [comment]
This would be neat. Could we merge it and release a new version?

**Comment by d4hines** [comment]
What will it take to get this merged? I saw the build failed on Mac, Node 8. Does that need to be fixed first? I'd like to use an official release of this for my project.

Thanks a ton!

**Comment by d4hines** [comment]
Actually, I see the fix has already been merged in a different PR. Now we just need a release.

**Comment by GabrielCastro** [comment]
done

**Pull request closed without merging**
